# Generated by Django 4.0.5 on 2022-11-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewreview',
            name='slug',
            field=models.SlugField(default='aryan', max_length=20),
            preserve_default=False,
        ),
    ]
