# Generated by Django 4.0.5 on 2022-11-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_interviewreview_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewreview',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
