# Generated by Django 4.0.5 on 2022-11-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_interviewreview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewreview',
            name='job_title',
            field=models.CharField(default='SDE', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewreview',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
