# Generated by Django 4.0.5 on 2022-06-28 18:56

from django.db import migrations, models
import user.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('reg_no', models.CharField(max_length=8, unique=True, validators=[user.models.validators.validate_reg_no])),
                ('username', models.CharField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('gender', models.PositiveIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], null=True)),
                ('active', models.BooleanField(default=True)),
                ('branch', models.PositiveIntegerField(choices=[(0, 'CSE')], null=True)),
                ('passing_year', models.DateField(null=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
